# Generated by Django 5.1.1 on 2024-09-20 10:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('event_created_on', models.DateField(default=datetime.date.today)),
                ('event_created_at', models.TimeField(default=datetime.time(10, 57, 46, 742199))),
                ('location', models.CharField(choices=[('BLR', 'Bangalore'), ('HYD', 'Hyderabad'), ('PUNE', 'Pune'), ('CHEN', 'Chennai')], max_length=4)),
                ('tickets_available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_shows.user')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book_shows.events')),
            ],
        ),
    ]
