# Generated by Django 5.1.1 on 2024-09-20 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shows', '0002_events_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_created_at',
            field=models.TimeField(default=datetime.time(11, 18, 58, 263451)),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(unique=True),
        ),
    ]
