# Generated by Django 5.1.1 on 2024-09-20 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_shows', '0003_alter_events_event_created_at_alter_events_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_created_at',
            field=models.TimeField(default=datetime.time(11, 19, 28, 215251)),
        ),
    ]
